image: node:10

variables:

stages:
  - install_deps
  - uat
  - prod

cache:
  key: ${CI_PROJECT_NAME}
  paths:
  - node_modules/
  - dist/

before_script:
- echo '开始构建......'
install_deps:
  stage: install_deps
  tags:
    - dianjue-admin-website
  only:
    - develop
    - /^release(_publish)?(\d*\_){2,}\d+$/
  #when:
  #  manual
  script:
    - npm config set registry https://registry.npm.taobao.org
    - npm install --global vue-cli
    - npm install --force
    - npm run build
prod:
  stage: prod
  only:
    - /^release_publish(\d*\_){2,}\d+$/
  tags:
    - dianjue-admin-website
  script:
   #- sshpass -p dianjue@1016 scp -o  StrictHostKeyChecking=no -r ./dist/* centos@192.168.1.63:/opt/magic-form-fe
   - sshpass -p dianjue@1016 ssh -o StrictHostKeyChecking=no centos@192.168.1.63 "cd /www/bus_one && sudo docker build -t registry.cn-shanghai.aliyuncs.com/dianjue/web:$CI_COMMIT_REF_NAME . && sudo docker push registry.cn-shanghai.aliyuncs.com/dianjue/web:$CI_COMMIT_REF_NAME"
   #- sshpass -p dianjue@1016 ssh -o StrictHostKeyChecking=no centos@192.168.1.63 'cd /opt && sudo docker build -t mq1.dj.com/dianjue/web:latest . && sudo docker push mq1.dj.com/dianjue/web:latest'
  when:
    manual
  before_script:
  - sudo apt-get clean && sudo apt-get update --fix-missing
  - echo "deb http://mirrors.aliyun.com/debian/ stretch main non-free contrib" >/etc/apt/sources.list && \
    echo "deb http://mirrors.aliyun.com/debian/ stretch-updates main non-free contrib" >>/etc/apt/sources.list && \
    echo "deb http://mirrors.aliyun.com/debian/ stretch-backports main non-free contrib" >>/etc/apt/sources.list && \
    echo "deb-src http://mirrors.aliyun.com/debian/ stretch main non-free contrib" >>/etc/apt/sources.list && \
    echo "deb-src http://mirrors.aliyun.com/debian/ stretch-updates main non-free contrib" >>/etc/apt/sources.list && \
    echo "deb-src http://mirrors.aliyun.com/debian/ stretch-backports main non-free contrib" >>/etc/apt/sources.list && \
    echo "deb http://mirrors.aliyun.com/debian-security/ stretch/updates main non-free contrib" >>/etc/apt/sources.list && \
    echo "deb-src http://mirrors.aliyun.com/debian-security/ stretch/updates main non-free contrib" >>/etc/apt/sources.list
  - apt-get update && apt-get install sshpass
  #- npm config set registry https://registry.npm.taobao.org
  #- npm install --global vue-cli
  #- npm install
  #- npm run build
build:
  stage: uat
  only:
    - /^release(_publish)?(\d*\_){2,}\d+$/
  #when:
  #  manual
  tags:
    - dianjue-admin-website
  script:
   - sshpass -p dianjue@1016 scp -o  StrictHostKeyChecking=no -r ./dist/* centos@192.168.1.63:/www/bus_one/dianjue-admin-website
   - sshpass -p dianjue@1016 ssh -o StrictHostKeyChecking=no centos@192.168.1.63 'sudo systemctl restart nginx'
  after_script:
  before_script:
  - echo "deb http://mirrors.aliyun.com/debian/ stretch main non-free contrib" >/etc/apt/sources.list && \
    echo "deb http://mirrors.aliyun.com/debian/ stretch-updates main non-free contrib" >>/etc/apt/sources.list && \
    echo "deb http://mirrors.aliyun.com/debian/ stretch-backports main non-free contrib" >>/etc/apt/sources.list && \
    echo "deb-src http://mirrors.aliyun.com/debian/ stretch main non-free contrib" >>/etc/apt/sources.list && \
    echo "deb-src http://mirrors.aliyun.com/debian/ stretch-updates main non-free contrib" >>/etc/apt/sources.list && \
    echo "deb-src http://mirrors.aliyun.com/debian/ stretch-backports main non-free contrib" >>/etc/apt/sources.list && \
    echo "deb http://mirrors.aliyun.com/debian-security/ stretch/updates main non-free contrib" >>/etc/apt/sources.list && \
    echo "deb-src http://mirrors.aliyun.com/debian-security/ stretch/updates main non-free contrib" >>/etc/apt/sources.list
  - apt-get update && apt-get install sshpass
build-dev:
  stage: uat
  only:
    - develop
  #when:
  #  manual
  tags:
    - dianjue-admin-website
  script:
   - echo 'old'
   - sshpass -p dianjue@1016 scp -o  StrictHostKeyChecking=no -r ./dist/* centos@192.168.1.94:/www/bus_one/dianjue-admin-website
   - sshpass -p dianjue@1016 ssh -o StrictHostKeyChecking=no centos@192.168.1.94 'sudo systemctl restart nginx'
  after_script:
  before_script:
  - echo "deb http://mirrors.aliyun.com/debian/ stretch main non-free contrib" >/etc/apt/sources.list && \
    echo "deb http://mirrors.aliyun.com/debian/ stretch-updates main non-free contrib" >>/etc/apt/sources.list && \
    echo "deb http://mirrors.aliyun.com/debian/ stretch-backports main non-free contrib" >>/etc/apt/sources.list && \
    echo "deb-src http://mirrors.aliyun.com/debian/ stretch main non-free contrib" >>/etc/apt/sources.list && \
    echo "deb-src http://mirrors.aliyun.com/debian/ stretch-updates main non-free contrib" >>/etc/apt/sources.list && \
    echo "deb-src http://mirrors.aliyun.com/debian/ stretch-backports main non-free contrib" >>/etc/apt/sources.list && \
    echo "deb http://mirrors.aliyun.com/debian-security/ stretch/updates main non-free contrib" >>/etc/apt/sources.list && \
    echo "deb-src http://mirrors.aliyun.com/debian-security/ stretch/updates main non-free contrib" >>/etc/apt/sources.list
  - apt-get update && apt-get install sshpass
after_script:
- echo '结束构建...'
